# permissions for end users to edit skydives.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydive-editor-role
rules:
- apiGroups:
  - skydive-group.example.com
  resources:
  - skydives
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skydive-group.example.com
  resources:
  - skydives/status
  verbs:
  - get
