apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: skydive-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Skydive is the Schema for the skydives API
      displayName: Skydive
      kind: Skydive
      name: skydives.skydive-group.example.com
      version: v1
  description: deploy skydive monitoring tool
  displayName: skydive-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - skydive
  links:
  - name: Skydive Operator
    url: https://skydive-operator.domain
  maintainers:
  - email: oran.nahoum1@ibm.com
    name: oran
  maturity: alpha
  provider:
    name: oran
  version: 0.0.0
